# .readthedocs.yaml
# Read the Docs configuration file (updated based on September 2023 migration)
# https://blog.readthedocs.com/migrate-configuration-v2/

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Specified dependencies
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
  - requirements: docs/requirements.txt
